---
title: "Untitled"
format:
  html:
    theme: default
---

#### Libs

```{r}
library(here)
library(tidyverse)
```

```{r}
here<- here::here
rename<- dplyr::rename
select<- dplyr::select
```

#### Data

```{r}
env<- read_csv(here('data', 'raw_data', "env_reps.csv"))
```

# Clean

```{r}
env<-
  env %>%
  filter(Level %in% "Surface") %>%
  select(!c("Notes", "Time")) %>%
  rename("Ammonium" = "Ammonia") %>%
  mutate(Site = recode(Site, "BO" = "Blind Oso",
                       "C2" = "Canals",
                       "RD6" = "Gulf"))
```

**Daily DF**

```{r}
daily<-
  env %>%
    filter(between(Date, as.Date('2022-07-07'), as.Date('2022-07-19')))

daily<-
  daily %>%
  mutate_at(vars(Conductivity, Salinity, DO_mgL, DO_perc, pH, Temperature, Water_depth, Secchi_depth, Chl_a, DOC, TDN, TOC, TN, Ammonium, NO2NO3, Nitrite, Orthophosphate, Silicate), as.numeric)
```

**Calculate other variables**

```{r}
daily<-
  daily %>%
  mutate(
    DIN = Ammonium + NO2NO3,
    DON = TDN - DIN,
    DIN_DIP =DIN / Orthophosphate)
```

# Save

```{r}
write_csv(daily,here('data', 'processed_data','env', 'ENV_REPS.csv' ))
```
