---
title: "Va copies calc"
format:
  html:
    theme: default
---
**FOR DAILY AND MONTHLY VA WRANGLING**

Libraries
```{r}
library(tidyverse)
library(here)
library(ggpubr)
```

Load data
```{r}
d<- read_csv(here("data", "raw_data", "va_daily.csv"))

m<- read_csv(here("data", "raw_data", "va_mon.csv"))
```

One sample was very contaminated(?) Cq = 1???
```{r}
d<- d %>%
  filter(!Well %in% "K06")
```

Separate out Monthly Inhibition from Regular
```{r}
inh<- 
  m %>% 
  filter(
    !grepl('i', Sample) |
    grepl('Pos', m$Content)) #Select only inhbition. Here I messed up CFX input. So samples with no 'i' are actually inhibition and vv

saveRDS(inh, file = here("data", "processed_data", "va_mon_inh.rds")) #Saves inhibition data set for analysis

#Make regular dataset with just samples. Again, I messed up with labeling, so we actually want the samples labeled with 'i' here. 
m<-
  m %>%
  filter(
    grepl('i', Sample)
  )
```


Create Site Column from Sample Name 
```{r}
d<- d %>%
  mutate(site = substr(d$Sample,1,2)) 

m<- m %>%
  mutate(site = substr(m$Sample,1,2)) 
```


Add Dilution Column and Filter column
```{r}
dilution<- d%>%
  mutate(dilution = case_when(site == "BO"~"1",
                              site  == "C2"~ "1",
                              site == "RD"~"1"),
         dilution = as.numeric(dilution))



filter<- dilution %>%
   mutate(filter_amt = case_when(
                          Sample == "BO7"~"100",
                          Sample == "BO8"~"100",
                          Sample == "BO9"~"100",
                          Sample == "BO9"~"100",
                          Sample == "BO11"~"100",
                          Sample == "BO12"~"50",
                          Sample == "BO13"~"50",
                          Sample == "BO14"~"50",
                          Sample == "BO15"~"50",
                          Sample == "BO16"~"30",
                          Sample == "BO17"~"30",
                          Sample == "BO18"~"30",
                          Sample == "BO19"~"30",
                              site  == "C2"~ "100",
                              site == "RD"~"100"),
          filter_amt = as.numeric(filter_amt)) 

dilution_m<- m%>%
  mutate(dilution = case_when(site == "BO"~"1",
                              site  == "C2"~ "1",
                              site == "RD"~"1"),
         dilution = as.numeric(dilution))



filter_m<- dilution_m %>%
   mutate(
     day = substr(dilution_m$Sample, 4,7),
     filter_amt = case_when(
                          site == "BO" & day == '2i' ~"100",
                          site == "BO" & day == '3i' ~ "100",
                          site == "BO" & day == '4i' ~ "100",
                          site == "BO" & day == '5_11' ~"100",
                          site == "BO" & day == '5_20' ~ "100",
                          site == "BO" & day == '5_24' ~ "100",
                          site == "BO" & day == '6i' ~"100",
                          site == "BO" & day == '8i'~ "30",
                          site == "BO" & day == '9i'~"45",
                          site == "BO" & day == '10i' ~ "60",
                          site == "BO" & day == '11i'~ "30",
                          site == "BO" & day == '12i'~ "60",
                          site  == "C2"~ "100",
                          site == "RD"~"100"),
       filter_amt = as.numeric(filter_amt))
```

Cq --> Copies/mL
```{r}
copies<- filter %>%
    mutate(
    log_sq = ((Cq-41.625)/-3.697), #Equation of the line to get log(SQ). Equation is 3/22/23 (e6--> e1)
    sq = 10^log_sq, #Unlog 
    copies_rxn = sq*15, #SQ*Reaction Volume
    copies_uL_1_10 = copies_rxn/1.2, #Copies/RXN / DNA Template Volume
    copies_uL_extract = copies_uL_1_10 *dilution, #(Copies/uL of 1:10)*(1 if there was no sample dilution // *10 if there was a 1:10 dilution etc.)
    concentration_factor = 100/filter_amt, #(Concentration factor = amount of eluted DNA from ZYMO) / (filter amount from vacuum filtration)
    copies_mL = copies_uL_extract*concentration_factor) %>%
    
select(Sample,copies_mL, site)

copies_m<- filter_m %>%
   mutate(
    log_sq = ((Cq-42.928)/-3.254), #Equation of the line to get log(SQ). Equation is 3/20/23
   sq = 10^log_sq, #Unlog 
    copies_rxn = sq*15, #SQ*Reaction Volume
    copies_uL_1_10 = copies_rxn/1.5, #Copies/RXN / DNA Template Volume
    copies_uL_extract = copies_uL_1_10 *dilution, #(Copies/uL of 1:10)*(1 if there was no sample dilution // *10 if there was a 1:10 dilution etc.)
    concentration_factor = 100/filter_amt, #(Concentration factor = amount of eluted DNA from ZYMO) / (filter amount from vacuum filtration)
    copies_mL = copies_uL_extract*concentration_factor) %>%
    
select(Sample,copies_mL, site,day)
```

Replace NaN with 0 for copies/mL
```{r}
replace<- copies %>%
 mutate(copies_mL = ifelse(is.na(copies_mL), 0, copies_mL)) %>%
filter(!is.na(Sample))   
 #Dropping NAs from STD Curve

replace_m<- copies_m %>%
 mutate(copies_mL = ifelse(is.na(copies_mL), 0, copies_mL)) %>%
filter(!is.na(Sample))   
 #Dropping NAs from STD Curve
```

Date Column
```{r}
date<- replace %>%
  mutate(day = substr(replace$Sample,3,4)) %>% #Creates new column `date`
  mutate(date = case_when(day == "7"~"2022-07-07",
                         day ==  "8"~"2022-07-08",
                         day ==  "9"~"2022-07-09",
                         day ==  "11"~"2022-07-11",
                         day == "12"~"2022-07-12",
                         day ==  "13"~"2022-07-13",
                         day ==  "14"~"2022-07-14",
                         day ==  "15"~"2022-07-15",
                         day ==  "16"~"2022-07-16",
                         day == "17"~"2022-07-17",
                         day ==  "18"~"2022-07-18",
                         day == "19"~"2022-07-19"))

date_m<- replace_m %>%
 mutate(date = case_when(day == "2i"~"2022-02-16",
                        day ==  "3i"~"2022-03-09",
                         day ==  "4i"~"2022-04-20",
                         day ==  "5_11"~"2022-05-11",
                         day == "5_20"~"2022-05-20",
                         day ==  "5_24"~"2022-05-24",
                         day ==  "6i"~"2022-06-13",
                         day ==  "8i"~"2022-08-09",
                         day ==  "9i"~"2022-09-13",
                         day == "10i"~"2022-10-18",
                         day ==  "11i"~"2022-11-15",
                         day == "12i"~"2022-12-14"))
```

Take the average of qPCR triplicates 
```{r}
final<- date %>% 
  group_by(site, Sample,date) %>% #Group all chr together. All that should be left out is the numeric vector we want to work with (in this case, copies_mL)
  summarize_if(is.numeric, mean) %>%
  ungroup() %>% #Ungroup to spit everything back out 
  select(date,copies_mL,site)

final_m<- date_m %>% 
  group_by(site, Sample,date, day) %>% #Group all chr together. All that should be left out is the numeric vector we want to work with (in this case, copies_mL)
  summarize_if(is.numeric, mean) %>%
  ungroup() %>% #Ungroup to spit everything back out 
 select(date,copies_mL,site)
```

Save as RDS and manually add date in excel
```{r}
#stop() #Write error so it wont overwrite
write.csv(final, file= here("data","processed_data","va_clean_copies_daily.csv"))

write.csv(final_m, file= here("data","processed_data","va_clean_copies_monthly.csv"))
```
