---
title: "megan lod"
format:
  html:
    theme: default
---

#### Libraries

```{r, include = FALSE}
library(here)
library(tidyverse)
```

#### Data

```{r, include = FALSE}
vib<- read_csv(here('data', 'raw_data', 'qpcr', 'lod_loq', 'megan', 'hf183.csv'))
```

# Clean

```{r}
vib <- 
  vib %>% 
  rename("ct" = "Cq") %>%
  select(c(Sample, ct)) %>%
  mutate(ct=as.numeric(ifelse(ct=="Undetermined", NA, ct)))
```

# LOQ/LOD

```{r}
#Determine the LOD and LOQ by plotting the Normal QQ-Plot
qqnorm.ct.vib <- qqnorm(vib$ct, plot.it = T) %>% as.data.frame()

tiff(filename = "figures/detection_lims.tiff", height = 9, width = 8, units = "in", res = 600)

#Create function to compute LOD and lOQ
qqnorm.Explorer.ct <- function(qqnorm.ct){
  qqnorm.ct <- qqnorm.ct[which(complete.cases(qqnorm.ct)),]
  qqnorm.ct <- qqnorm.ct[order(qqnorm.ct$x),]
  qqnorm.ct <- cbind(qqnorm.ct, rbind(NA, qqnorm.ct[-nrow(qqnorm.ct),])) %>% setNames(., nm = c("x", "y", "x-1", "y-1"))
  qqnorm.ct %<>% mutate(rise = y-`y-1`, run = x-`x-1`) %>% mutate(slope = rise / run)
  qqnorm.ct$lod <- NA
  qqnorm.ct$loq <- NA
  prev.slope <- 1
  lod.found <- 0
  for(i in nrow(qqnorm.ct):2){
    if(lod.found==0){
      if(qqnorm.ct$slope[i]<1 & prev.slope <1){
        qqnorm.ct$lod[i] <- 1
        lod.found <- 1
      }else{
        prev.slope <- qqnorm.ct$slope[i]
      }
    }
    if(lod.found==1){
      if(qqnorm.ct$slope[i]>1){
        qqnorm.ct$loq[i] <- 1
        break
      }else{
        prev.slope <- qqnorm.ct$slope[i]
      }
    }
  }
  lod.ct <- qqnorm.ct$y[which(qqnorm.ct$lod==1)]
  loq.ct <- qqnorm.ct$y[which(qqnorm.ct$loq==1)]
  return(list(qqnorm.dataset = qqnorm.ct, lod = lod.ct, loq = loq.ct))
}

#Run function on each data set
qqnorm.ct.vib <- qqnorm.Explorer.ct(qqnorm.ct.vib)

#Save LOD and LOQ for each data set
vib_stepone_lod <- qqnorm.ct.vib$lod
vib_stepone_loq <- qqnorm.ct.vib$loq

```
