---
title: "species cleaning"
format:
  html:
    theme: default
---

```{r}
library(tidyverse)
library(here)
```

```{r, include = FALSE}
va<- read_csv(here('data', 'processed_data', 'qpcr', 'for_real', 'va_final.csv'))
vc<- read_csv(here('data', 'processed_data', 'qpcr', 'for_real', 'vc_final.csv'))
vp<- read_csv(here('data', 'processed_data', 'qpcr', 'for_real', 'vp_final.csv'))
vv<- read_csv(here('data', 'processed_data', 'qpcr', 'for_real', 'vv_final.csv'))
```

```{r}
vp$date[vp$date == "2022-06-13"] <- "2022-06-14" 
```

```{r}
va<- 
  va %>%
  rename("Va" = "copies_mL")
vc<- 
  vc %>%
  rename("Vc" = "copies_mL")
vv<- 
  vv %>%
  rename("Vv" = "copies_mL")
vp<- 
  vp %>%
  rename("Vp" = "copies_mL")
```

```{r}
species_final0<-
  left_join(va,vc,  by= c("site","date"))

species_final1<-
  left_join(vv,vp,  by= c("site","date"))

species_final<-
  left_join(species_final1, species_final0, by = c("site", "date"))
```

```{r}
write_csv(species_final, here("data", "processed_data", "qpcr", "species_all.csv"))
```
