---
title: "dust_2022"
format:
  html:
    theme: default
---

# Intro

#### Libs

```{r, include = FALSE}
library(here)
library(tidyverse)
library(ggpubr)
library(lubridate)
```

#### Data

```{r}
dust<-read_csv(here("data", "processed_data", "tx_master.csv")) 
```

# Clean

#### Select Columns

```{r}
dust<-
  dust %>%
  select(Dust, date, SUM, Type)
```

#### Make Month df for viewing monthly sampling time points

```{r}
month<- dust %>%
  filter(Type %in% "Monthly") #%>%
# filter(between(date, as.Date('2022-02-01'), as.Date('2022-08-28')))
```

# Plot

#### 2022

```{r}
dust %>%
  filter(date %in% as.Date('2022-02-01') : as.Date('2022-12-15'))%>%
  ggplot() + geom_line(
    aes(x = date,
        y = SUM)) +
  theme_bw()+
  labs(
    title = "Dust Aerosol Optical Density in 2022",
    x = "Month",
    y = "Dust AOD")+
  theme(plot.title = element_text(hjust = 0.5)) +
  geom_vline(xintercept = as.Date("2022-07-07"), color = "4c848c", size = 0.8, linetype = "dotdash") +
  geom_vline(xintercept = as.Date("2022-07-19"), color = "4c848c", size =0.8, linetype =    "dotdash") +
  scale_x_date(date_breaks = "1 month", date_labels = "%b") +
  geom_point(data = month,
             aes(x = date,
                 y = SUM),
             shape = 4,
             size = 3,
             color = "4c848c",
             stroke = 1)

ggsave(here("results", "plots", "dust_2022.png"))
```

#### July Whole Month 

```{r}
dust %>%
  filter(date %in% as.Date('2022-07-01') : as.Date('2022-07-31'))%>%
  ggplot() + geom_line(
    aes(x = date,
        y = SUM)) +
  theme_bw()+
  labs(
    title = "Dust Aerosol Optical Density in July 2022",
    x = "",
    y = "Dust AOD")+
  theme(plot.title = element_text(hjust = 0.5),
        axis.text.x = element_text(hjust= 1, angle = 45))  + 
  scale_x_date(date_breaks = "2 day", date_labels = "%b %d")
 
```

#### May Dust Event

```{r}
dust %>%
  filter(date %in% as.Date('2022-05-01') : as.Date('2022-06-01'))%>%
  ggplot() + geom_line(
    aes(x = date,
        y = SUM)) +
  theme_bw()+
  labs(
    title = "Dust Aerosol Optical Density in May 2022",
    x = "Date",
    y = "Dust AOD")+
  theme(plot.title = element_text(hjust = 0.5)) 
  #scale_x_date(date_breaks = "1 month", date_labels = "%b") +


ggsave(here("results", "plots", "dust_may_2022.png"))
```
