---
title: "cfu_total_dust"
format:
  html:
    theme: default
---

#### Libraries

```{r}
library(Rmisc)
library(tidyverse)
library(here)
library(ggpubr)
library(cowplot)
library(gridExtra)
library(scales)
library(ggthemes)

```

```{r}
here<- here::here
select<-dplyr::select
```

#### Data

```{r, include = FALSE}
dust<- read_csv(here("data", "processed_data", "dust", "dust_master.csv"))
data<- read_csv(here("data", "processed_data", "tx_master.csv"))
vc<- read_csv(here::here("data", "processed_data",  "ANOVA Data", "vc_anova.csv"))
```

# Clean

#### Select and Filter

```{r}
data<-
  data %>%
  filter(Type %in% "Daily",
         hr_cst %in% "01") %>%
  dplyr::select(copies_mL, cfu_tot, site, date)
```

# Plot

#### Color-blind pallete: https://personal.sron.nl/\~pault/#sec:qualitative

```{r}
cbbPalette <- c("#DDAA33", "#BB5566", "#004488" )
show_col(colorblind_pal()(8))

```

#### CFU

```{r}
cfu<-
  data %>%
  ggplot() + 
  geom_line(
    aes(x = date,
        y = cfu_tot,
        color = site),
        size =1) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))+
  scale_color_manual(values = cbbPalette) +
  theme_bw() +
  labs(x = "Date",
       y = "CFU/mL")+
  theme(axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        legend.position = "none")
cfu
```

#### Total Vibrio

```{r}
vib<-
  data %>%
  ggplot() + 
  geom_line(
    aes(x = date,
        y = copies_mL,
        color = site)) +
 #facet_wrap(~site)+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))+
  scale_color_manual(values = cbbPalette) +
  theme_bw() +
  labs(y = "Total Vibrio copies/mL")+
  theme(axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        legend.position = "none")
vib
```

#### Dust

```{r, fig.width=5}
d<- 
  dust %>%
  filter(between(date, as.Date('2022-07-07'),  as.Date('2022-07-19'))) %>%
  ggplot()+ geom_line(
    aes(x = date,
        y = t7sum)) +
  theme_bw() +
  scale_x_date(date_breaks = "2 day", date_labels = "%b %d")+
  labs(x = "Date",
       y = "Dust AOD")
```

#### Combine

```{r}
master_fig<-
  ggarrange(cfu,vib,d,
            nrow = 3,
            ncol = 1,
            align = "v")

master_fig

ggsave(here("results", "plots", "dust_cfu_total.png" ))
```

# Now do the same thing with boxplots

#### Data

```{r, include = FALSE}
cfu<- read_csv(here('data', 'processed_data', 'cfu', 'cfu_anova.csv'))
copies<- read_csv(here("data", "processed_data",  "ANOVA Data", "daily_anova_data.csv"))
dust<- read_csv(here("data", "processed_data", "dust", "dust_master.csv"))

```

```{r}
cfu<-
  cfu %>%
  filter(between(date, as.Date("2022-07-07") , as.Date("2022-07-19")))%>%
  mutate(site = recode(site, 
                       "BO" = "Blind Oso",
                       "C2" = "Canals",
                       "RD" = "Gulf"))
```

#### CFU

```{r, fig.width=5}
  cf<-
    cfu %>%
  ggplot() + geom_boxplot(
    aes(x = date,
        y = cfu_mL,
        color= site,
        group = interaction(date, site)),
        position = "identity") +
  theme_bw()+
  theme(axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        legend.position = "none",
        axis.title.y = element_text(face = "bold"))+
      #  legend.background = element_rect(fill = "lightblue",
       #                                  size = 0.5,
        #                                 linetype = "solid",
         #                                colour = "darkblue"),
        #legend.key.size = unit(0.1, 'cm')) +
  scale_x_date(breaks = "2 day", date_labels = "%b %d")+
  labs(x = "Date",
       y = "CFU/mL",
       color = "Site",
       tag = "A") +
  scale_color_manual(values = cbbPalette )+
     
stat_summary(fun=mean, geom="line", 
             aes(x = date, 
                 y = cfu_mL,
                 group=site, 
                 color = site))  
  
  cf
```

#### Copies per mL

```{r}
cop<-
  copies %>%
  ggplot() + geom_boxplot(
    aes(x = date,
        y = copies_mL,
        color= site,
        group = interaction(date, site)),
        position = "identity") +
  theme_bw()+
  labs(x = "Date",
       y = "Total Vibrio (copies/mL)",
       tag = "B") +
  theme(axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        legend.position = "none",
        axis.title.y = element_text(face = "bold"))+
  scale_x_date(breaks = "2 day", date_labels = "%b %d")+
  scale_color_manual(values = cbbPalette)+


#(aes(x=as.Date('2022-07-12'),xend=as.Date('2022-07-18'),y=154323
#,yend=154323), color = "#4c848c", size = 2)+
#annotate("text", x = as.Date('2022-07-15'), y =155000, label = "***", color = "#4c848c", fontface="bold", size = 7)+

#geom_segment(aes(x=as.Date('2022-07-12'),xend=as.Date('2022-07-14'),y=90000
#,yend=90000), color = "#809C52", size = 2)+
#annotate("text", x = as.Date('2022-07-13'), y =91000, label = "***", color = "#809C52", fontface="bold", size = 7)+
  
stat_summary(fun=mean, geom="line", 
             aes(x = date, 
                 y = copies_mL,
                 group=site, 
                 color = site)) 
cop
```

#### Dust as a box plot

```{r}
dust<- 
  dust %>%
  filter(between(date, as.Date('2022-07-07'),  as.Date('2022-07-19'))) 
  
du_box<-
  dust %>%
  ggplot()+ geom_boxplot(
    aes(x = date,
        y = t7sum,
        group = date), 
    position = "identity",
    size = 0) +
  theme_bw() +
  scale_x_date(date_breaks = "2 day", date_labels = "%b %d")+
  labs(x = "Date",
       y = "Dust AOD",
       tag = "C") +
  theme(axis.title.y = element_text(face = "bold"))+
  
geom_line(
  aes(
    x = date,
    y = t7sum
  )
)

du_box
```

#### Combine

```{r, fig.height=3.5, fig.width=3}
master_box<-
ggarrange(cf,cop,du_box,
            nrow = 3,
            ncol = 1,
          align = "v",
          common.legend = TRUE)

master_box

ggsave(here("results", "plots", "dust_cfu_total_boxplots.png" ))
```

# Plot: Point and SE

#### CFU

```{r}
pd <- position_dodge(0.1) # move lines .05 to the left and right

cfu<-
  cfu %>%
  select(site, date, cfu_mL) 

cfu_sum<- 
  summarySE(cfu, measurevar="cfu_mL", groupvars=c("site", "date"))
```

```{r}
cfu_p<-
ggplot(cfu_sum, 
       aes(x=date, 
           y=cfu_mL, 
           color=site)) + 
    geom_errorbar(
      aes(ymin=cfu_mL-se, 
          ymax=cfu_mL+se), 
      width=.5) +
    geom_line() +
    geom_point() +
  theme_bw()+
  labs(y = "CFU/mL",
       color = "Site")+
  scale_x_date(date_breaks = "2 day", date_labels = "%b %d")+
  scale_color_manual(values = c("Blind Oso" = "#809C52",
                                "Canals" = "#ba4716",
                                "Gulf" = "#4c848c"))+
  theme(axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.title.x = element_blank(),
        legend.position = "none")
cfu_p
```

#### Total Vibrio

```{r}
copies<-
  copies %>%
  select(!Type) %>%
  mutate(site = recode(site, 
                       "BO" = "Blind Oso",
                       "C2" = "Canals",
                       "RD" = "Gulf"))

copies_sum<- 
  summarySE(copies, measurevar="copies_mL", groupvars=c("site", "date"))
```

```{r}
cop_p<-
ggplot(copies_sum, 
       aes(x=date, 
           y=copies_mL, 
           color=site)) + 
    geom_errorbar(
      aes(ymin=copies_mL-se, 
          ymax=copies_mL+se), 
      width=.5) +
    geom_line() +
    geom_point() +
  theme_bw()+
  labs(y = "Gene copies/mL",
       color = "Site")+
  scale_x_date(date_breaks = "2 day", date_labels = "%b %d")+
  scale_color_manual(values = c("Blind Oso" = "#809C52",
                                "Canals" = "#ba4716",
                                "Gulf" = "#4c848c"))+
  theme(axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.title.x = element_blank(),
        legend.position = "none")
cop_p
```

#### Dust as a line plot

```{r}
du_p<-
ggplot(du_sum, 
       aes(x=date, 
           y=t7sum)) + 
    geom_errorbar(
      aes(ymin=0, 
          ymax=0), 
      width=0, 
      position=pd) +
    geom_line(position=pd) +
  theme_bw()+
  labs(y = "Dust AOD",
       x = "Date")+
  scale_x_date(date_breaks = "2 day", date_labels = "%b %d")+
  theme(#axis.text.x = element_blank(),
        #axis.ticks.x = element_blank(),
        #axis.title.x = element_blank(),
        legend.position = "none")
du_p
```

#### Combine

```{r}
master_point<-
ggarrange(cfu_p, cop_p, du_box, 
          ncol=1,
          nrow =3,
          align = "v")

master_point
```
