---
title: "COVIS"
format:
  html:
    theme: default
---

#### Libs

```{r}
library(tidyverse)
library(here)
```

```{r}
here<- here::here
select<- dplyr::select
```

#### Data

```{r}
covis<- read_csv(here('data', 'processed_data', 'COVIS.csv')) #1997-2019
cov_2019<- read_csv(here('data', 'processed_data', 'covis_2019.csv')) #2019 report
```

# Clean

#### 2019 Report

```{r}
cov_2019<- head(cov_2019,18) %>%#Gets rid of probable cases
  filter(!species %in% c("Multiple Species","Confirmed"))

```

```{r}
tx<-
  covis %>%
  filter(STATE %in% "TX")

vp_tx<-
  covis %>%
  filter(STATE %in% "TX",
         SpeciesDesignation %in% "PAR")

vv_tx<-
  covis %>%
  filter(STATE %in% "TX",
         SpeciesDesignation %in% "VUL")

e_coast<-covis %>%
  filter(STATE %in% c("TX", "LA", "FL", "GA", "SC", "AL", "MS")) 
```

# Plot

#### US

```{r}
covis %>% 
ggplot()+ geom_bar(
  aes(x = Year,
      fill = SpeciesDesignation))+
  labs(x = "",
       y = "Case Count",
       fill = "Species",
       title = "Vibrio Case Count in US")+ 
    theme_bw()
```

```{r}
ljh<-
  covis %>%
  filter(Year %in% "2018")
```

#### Texas Cases

```{r}
tx %>% 
ggplot()+ geom_bar(
  aes(x = Year,
      fill = SpeciesDesignation))+
  labs(x = "",
       y = "Case Count",
       fill = "Species",
       title = "Vibrio Case Count in Texas")+ 
    theme_bw()
```

```{r}
vp_tx %>%
  ggplot()+
  geom_bar(
    aes(x = Month,
        color = Year)
  )
```

#### Case Count per state (SE)

```{r}
e_coast %>%
  ggplot() + 
  geom_bar(
    aes(x = Year,
        #color = STATE,
        fill = STATE)) + 
  scale_x_continuous(n.breaks = 20) + 
  theme_bw()+
  labs(x = "",
       y = "Case Count",
       color = "State",
       title = "Vibrio case count in Saharan-dust-downwind states")
```

# 2019 Report

```{r}
clr<- c("red", "red", "red", "red")
```

```{r}
cov_2019 %>%
  ggplot() +
  geom_bar(
    aes(x = reorder(species, -cases),
        y = cases,
        fill = big),
    stat = "identity")+
  theme_bw()+
  theme(axis.text.x = element_text(hjust = 1, angle = 50),
        legend.position = "none")+
  labs(x = "Species",
       y = "Confirmed Case Number",
       title = "COVIS Annual Summary in the U.S (2019)",
       caption = "*Excluding O1 and O139 serotypes") 
```
