---
title: "ANOVA"
format:
  html:
    theme: default
---

https://www.r-bloggers.com/2021/08/how-to-perform-tukey-hsd-test-in-r/

#### Libraries

```{r}
library(here)
library(tidyverse)
library(multcomp)
```

#### Data

Note: This data is pridced in total_copies_calculator code. I kept qPCR triplicates (i.e. did not average) for this

```{r, include = FALSE}
d<- read_csv(here("data", "processed_data", "qpcr", "daily_anova_data"))
```

# Clean

#### Subselect datasets

```{r}
d<-
  d %>%
  mutate(date = substr(date, 9,10)) #Date needs to not be as.Date format
b<-
  d %>%
  filter(site %in% "BO") %>%
  dplyr::select(date, copies_mL)  
c<-
  d %>%
  filter(site %in% "C2") %>%
  dplyr::select(date, copies_mL)

r<-
  d %>%
  filter(site %in% "RD") %>%
  dplyr::select(date, copies_mL)
```

# Stats

#### AOV

```{r}
b_aov<- 
  aov(copies_mL ~ date, data = b)

c_aov<- 
  aov(copies_mL ~ date, data = c)

r_aov<- 
  aov(copies_mL ~ date, data = r)
```

#### Tukey HSD

```{r}
TukeyHSD(b_aov, conf.level=.95)
TukeyHSD(c_aov, conf.level=.95)
TukeyHSD(r_aov, conf.level=.95)
```
