---
title: "va inh mon"
format:
  html:
    theme: default
---

Lib
```{r}
library(here)
library(tidyverse)
library(lubridate)
```

```{r}
va_m<- readRDS(file = here("data", "processed_data", "va_mon_inh.rds"))
```


Clean
```{r}
inh<- va_m %>%
  mutate(day = substr(va_m$Sample, 4,7),
         site = substr(va_m$Sample, 1,2))
inh<- inh %>%
  mutate(date = case_when(
                          inh$day == "2" ~ "2022-02-16",
                          inh$day == "3" ~ "2022-03-09",
                          inh$day == "4" ~ "2022-04-20",
                          inh$day == "5_11" ~ "2022-05-11",
                          inh$day == "5_20" ~ "2022-05-20",
                          inh$day == "5_24" ~ "2022-05-24",
                          inh$day == "6" ~ "2022-06-14",
                          inh$day == "8" ~ "2022-08-09",
                          inh$day == "9" ~ "2022-09-13",
                          inh$day == "10" ~ "2022-10-18",
                          inh$day == "11" ~ "2022-11-16",
                          inh$day == "12" ~ "2022-12-15"))

```

Plot
```{r}
inh %>%
  ggplot() + geom_boxplot(
    aes(x = date,
        y = Cq,
        color = site)) +
      theme_bw()+
  geom_hline(yintercept = 28.6)+
  theme(
    axis.text.x = element_text(hjust = 1, angle = 45))

```
