---
title: "vp_mon_inh"
format:
  html:
    theme: default
---

Lib
```{r}
library(here)
library(tidyverse)
library(lubridate)
```

```{r}
vv<- read_csv(here("data", "raw_data","vv_mon.csv"))
```


Clean
```{r}
inh<- vv %>%
  filter(Fluor %in% "HEX")  %>%
  mutate(type = case_when(grepl("i", Sample) ~ "inh"),
         day = substr(inh$Sample, 4,7),
         site = substr(inh$Sample, 1,2),
         date = case_when(inh$day == "2" ~ "2022-02-16",
                          inh$day == "2_i" ~ "2022-02-16",
                          inh$day == "3" ~ "2022-03-09",
                          inh$day == "3_i" ~ "2022-03-09",
                          inh$day == "4" ~ "2022-04-20",
                          inh$day == "4_i" ~ "2022-04-20",
                          inh$day == "5_11" ~ "2022-05-11",
                          inh$day == "5_20" ~ "2022-05-20",
                          inh$day == "5_24" ~ "2022-05-24",
                          inh$day == "6" ~ "2022-06-14",
                          inh$day == "6_i" ~ "2022-06-14",
                          inh$day == "8" ~ "2022-08-09",
                          inh$day == "8_i" ~ "2022-08-09",
                          inh$day == "9" ~ "2022-09-13",
                          inh$day == "9_i" ~ "2022-09-13",
                          inh$day == "10" ~ "2022-10-18",
                          inh$day == "11" ~ "2022-11-16",
                          inh$day == "12" ~ "2022-12-15"))

```

Plot
```{r}
inh %>%
  filter(type %in% "inh") %>%
  ggplot() + geom_boxplot(
    aes(x = date,
        y = Cq,
        color = site)) +
  geom_hline(yintercept = 25.7)

```
