---
title: "VAI"
format:
  html:
    theme: default
---

**Viz VAI**

```{r}
here<-here::here
select<- dplyr::select
rename<- dplyr::rename
```

# Intro

#### LIbrary

```{r}
library(here)
library(tidyverse)
```

#### Data

```{r, include = FALSE}
master<- read_csv(here::here("data", "processed_data", "tx_master.csv"))
dust<- read_csv(here("data", "processed_data", "dust", "dust_master.csv"))
```

# Cleaning

#### Daily DF

```{r}
daily<-
  master %>%
  filter(date %in% as.Date('2022-07-07') : as.Date('2022-07-19'),
         hr_cst %in% "01",
         !date %in% as.Date('2022-07-10'))
```

#### Monthly DF

```{r}
monthly<-
  master %>%
  filter(Type %in% "Monthly" | date %in% as.Date('2022-07-18'),
         hr_cst %in% c("00", "01"))
```

```{r}
dust<-
  dust %>%
  mutate(LAG = lag(t7sum, 1)) %>%
  filter(between(date, as.Date('2022-07-07'), as.Date('2022-07-19'))) 
```

# Plot

```{r}
cbbPalette <- c("#DDAA33", "#BB5566", "#004488" )
```

#### Daily Total Bacteria

```{r}
daily %>%
  ggplot() + geom_line(
    aes(x = date,
        y = log10(tot_bacteria),
        color = site),
    size = 1)+
  facet_wrap(~site) +
  theme_bw() + 
  labs(title = "Daily Total Bacteria",
       x = "Date",
       y = "Log10(Total Bacteria copies/mL)",
       color = "Site")+
  theme(plot.title = element_text(hjust = 0.5),
        axis.title.y = element_text(face = "bold"),
        axis.title.x = element_text(face = "bold"),
        axis.text.x = element_text(angle = 45, hjust = 1)) +
  scale_color_manual(values = cbbPalette) +
  scale_x_date(date_breaks = "2 day", date_labels = "%b%d")
  
ggsave(here("results", "plots", "qpcr", "total_bacteria.png"))
```

#### Clean DF for writing

```{r}
clean <-
  daily %>%
  filter(hr_cst %in% "01") %>%
  dplyr::select(site, date,VAI)

b<-
  clean %>%
  filter(site %in% "Blind Oso")

c<-
  clean %>%
  filter(site %in% "Canals")

r<-
  clean %>%
  filter(site %in% "Gulf")
```

```{r}
mean(b$VAI)
mean(r$VAI)
mean(c$VAI)
```

#### Daily VAI

```{r}
cbbPalette <- c("#DDAA33", "#BB5566", "#004488")
```

```{r}
daily %>%
  ggplot() + geom_bar(
    aes(x = date,
        y = VAI,
        fill = site),
    color = "black",
    stat = "identity") +
  facet_wrap(~site) +
  theme_bw() + 
  labs(fill = "Site",
       x = "Date")+
  theme(plot.title = element_text(hjust = 0.5),
        axis.title.y = element_text(face = "bold"),
        axis.title.x = element_text(face = "bold"),
        axis.text.x = element_text(angle = 45, hjust = 1)) +
  scale_fill_manual(values = cbbPalette) +
  scale_x_date(date_breaks = "2 day", date_labels = "%b%d")

  ggsave(here("results", "plots", "qpcr", "vai.png"))
```

#### Monthly Total Bacteria

```{r}
monthly %>%
  ggplot() + geom_line(
    aes(x = date,
        y = log10(tot_bacteria),
        color = site),
    size = 1)+
geom_point(
    aes(x = date,
        y = log10(tot_bacteria),
        color = site),
    size = 2) +
  facet_wrap(~site) +
  theme_bw() + 
  labs(title = "Monthly Total Bacteria",
       x = "Date",
       y = "Log10(Total Bacteria copies/mL)",
       color = "Site")+
  theme(plot.title = element_text(hjust = 0.5),
        axis.title.y = element_text(face = "bold"),
        axis.title.x = element_text(face = "bold"),
        axis.text.x = element_text(angle = 45, hjust = 1)) +
  scale_color_manual(values = c("Blind Oso" = "#809C52",
                                "Canals" = "#ba4716",
                                "Gulf" = "4c848c")) 
  
ggsave(here("results", "plots", "qpcr", "total_bacteria_monthly.png"))
```

```{r}
monthly %>%
  ggplot() + geom_bar(
    aes(x = date,
        y = VAI,
        fill = site),
    color = "black",
    stat = "identity",
    width = 20) +
  facet_wrap(~site) +
  theme_bw() + 
  labs(title = "Monthly VAI",
       fill = "Site",
       x = "Date")+
  theme(plot.title = element_text(hjust = 0.5),
        axis.title.y = element_text(face = "bold"),
        axis.title.x = element_text(face = "bold"),
        axis.text.x = element_text(angle = 45, hjust = 1)) +
  scale_fill_manual(values = c("Blind Oso" = "#809C52",
                                "Canals" = "#ba4716",
                                "Gulf" = "4c848c")) 

  ggsave(here("results", "plots", "qpcr", "vai_monthly.png"))
```

<!--# NEED TO RECHECK MELTCURVES -->

#### Total Bacteria Box plot

```{r}
bac<-read_csv(here('data', 'processed_data', 'ANOVA Data', 'total_bacteria.csv'))
```

```{r}
bac<-
  bac %>%
  mutate(site = recode(site, "BO" = "Blind Oso",
                       "C2" = "Canals",
                       "RD" = "Gulf"),
         copies_mL = log10(copies_mL)) %>%
  rename("Site" = "site" )
```

```{r}
bac %>%
  ggplot()+
  geom_boxplot(
    aes(x = date,
        y = copies_mL,
        color = Site,
        group = interaction(Site,date)),
    position = "identity")+
  scale_color_manual(values = cbbPalette) +
stat_summary(fun=mean, geom="line", 
             aes(x = date, 
                 y = copies_mL,
                 group=Site, 
                 color = Site)) +
  theme_bw()+
  labs(x = "Date",
       y = "log10(copies/mL)",
       color = "Site")+
  scale_x_date(date_breaks = "1 day", date_labels = "%b %d")
  
```

#### Boxplot by site

```{r}
means <- aggregate(copies_mL ~  Site, bac, mean)

din_comp <- list( c("Blind Oso", "Canals"), c("Blind Oso", "Gulf"), c("Canals", "Gulf") )

ggboxplot(bac, x = "Site",
          y = "copies_mL",
          color = "Site")+
    scale_color_manual(values = cbbPalette)+
  labs(y = "copies/mL")+ 
  theme(legend.position = "none")+
 stat_compare_means(comparisons = din_comp)+ 
  stat_summary(fun=mean, colour= cbbPalette, geom="point", 
               shape=18, size=3, show.legend=FALSE,) + 
  geom_text(data = means, aes(label = round(copies_mL,2), y = copies_mL + 4))
```

```{r}
gu<-
  bac %>%
  filter(Site %in% "Gulf") %>%
  ggplot()+
  geom_boxplot(
    aes(x = date,
        y = copies_mL,
        color = Site,
        group = interaction(Site,date)),
    position = "identity")+
  scale_color_manual(values = "#004488") +
stat_summary(fun=mean, geom="line", 
             aes(x = date, 
                 y = copies_mL,
                 group=Site, 
                 color = Site)) +
  theme_bw()+
  labs(x = "Date",
       y = "log10(copies/mL)",
       color = "Site")+
  scale_x_date(date_breaks = "1 day", date_labels = "%b %d")+
  theme(legend.position = "none")

 du<-
   dust %>%
  ggplot()+
  geom_boxplot(
    aes(x = date,
        y = t7sum,
        group = interaction(date)),
    size = 0,
    position = "identity")+
  scale_color_manual(values = "#004488") +
stat_summary(fun=mean, geom="line", 
             aes(x = date, 
                 y = t7sum)) +
  theme_bw()+
  labs(x = "Date",
       y = "Dust AOD",
       color = "Site")+
  scale_x_date(date_breaks = "1 day", date_labels = "%b %d")
 
  du_lag<-
   dust %>%
  ggplot()+
  geom_boxplot(
    aes(x = date,
        y = LAG,
        group = interaction(date)),
    size = 0,
    position = "identity")+
  scale_color_manual(values = "#004488") +
stat_summary(fun=mean, geom="line", 
             aes(x = date, 
                 y = LAG)) +
  theme_bw()+
  labs(x = "Date",
       y = "Dust Lag AOD",
       color = "Site")+
  scale_x_date(date_breaks = "1 day", date_labels = "%b %d")

```

```{r}
ggarrange(du, gu,du_lag,
          ncol = 1, nrow =3,
          align = "v")
```
