---
title: "Species boxplots"
format:
  html:
    theme: default
---

**Run this after cleaning qPCR code, and running LOD µL to assay code**

#### Libraries

```{r}
library(here)
library(tidyverse)
library(Rmisc)#For stat summary
library(ggpubr)
library(ggforce)
```

```{r}
here<- here::here
rename<- dplyr::rename
select<- dplyr::select
```

#### Data

**This species qPCR data contains all of the technical triplicates from qPCR. BO_Vc does have 5 triplicates**

```{r, include = FALSE}
va<- read_csv(here('data', 'processed_data', 'ANOVA Data', 'va_anova.csv'))
vc<- read_csv(here('data', 'processed_data', 'ANOVA Data', 'vc_anova.csv'))
vv<- read_csv(here('data', 'processed_data', 'ANOVA Data', 'vv_anova.csv'))
vp<- read_csv(here('data', 'processed_data', 'ANOVA Data', 'vp_anova.csv'))

#Above/Below Data from LOD µL to assay code
va1<- read_csv(here('data', 'processed_data', 'qpcr', 'LOD', 'va_above_below.csv'))
vc1<- read_csv(here('data', 'processed_data', 'qpcr', 'LOD', 'vc_above_below.csv'))
vp1<- read_csv(here('data', 'processed_data', 'qpcr', 'LOD', 'vp_above_below.csv'))
vv1<- read_csv(here('data', 'processed_data', 'qpcr', 'LOD', 'vv_above_below.csv'))
```

# Clean

#### Va

```{r}
va<- 
  va %>% #Add Date Column
  mutate(day = substr(Sample, 2,3),
   date = case_when(day == "7"~"2022-07-07",
                         day ==  "8"~"2022-07-08",
                         day ==  "9"~"2022-07-09",
                         day ==  "11"~"2022-07-11",
                         day == "12"~"2022-07-12",
                         day ==  "13"~"2022-07-13",
                         day ==  "14"~"2022-07-14",
                         day ==  "15"~"2022-07-15",
                         day ==  "16"~"2022-07-16",
                         day == "17"~"2022-07-17",
                         day ==  "18"~"2022-07-18",
                         day == "19"~"2022-07-19")) %>%
  filter(!is.na(date)) %>%
  select(date, copies_mL, site) %>%
  mutate(date = as.Date(date),
         site = recode(site, "BO" = "Blind Oso",
                       "C2" = "Canals",
                       "RD" = "Gulf"))

```

#### Vc

```{r}
vc<-
  vc %>%
  select(copies_mL, date, site)%>%
  mutate(date = as.Date(date),
         site = recode(site, "BO" = "Blind Oso",
                       "C2" = "Canals",
                       "RD" = "Gulf"))
```

#### Vv

```{r}
vv<-
  vv %>%
  select(date, copies_mL, site) %>%
  drop_na()%>%
  mutate(date = as.Date(date),
         site = recode(site, "BO" = "Blind Oso",
                       "C2" = "Canals",
                       "RD" = "Gulf"))
```

#### Vp

```{r}
vp<-
  vp %>%
  select(copies_mL, Sample, site) %>% #Add Date Column
  mutate(
    site = substr(Sample, 1,2),
    day = substr(Sample, 4,5),
    date = case_when(day == "7"~"2022-07-07",
                         day ==  "8"~"2022-07-08",
                         day ==  "9"~"2022-07-09",
                         day ==  "11"~"2022-07-11",
                         day == "12"~"2022-07-12",
                         day ==  "13"~"2022-07-13",
                         day ==  "14"~"2022-07-14",
                         day ==  "15"~"2022-07-15",
                         day ==  "16"~"2022-07-16",
                         day == "17"~"2022-07-17",
                         day ==  "18"~"2022-07-18",
                         day == "19"~"2022-07-19")) %>%
  filter(!is.na(date)) %>%
  select(date, copies_mL, site) %>%
  mutate(date = as.Date(date),
         site = recode(site, "BO" = "Blind Oso",
                       "C2" = "Canals",
                       "RD" = "Gulf"))
```

# Make Stat Summaries

```{r}
va_sum <- summarySE(va, measurevar="copies_mL", groupvars=c("site", "date")) %>%
  filter(site %in% "Canals") #Non-detects at this site

vc_sum <- summarySE(vc, measurevar="copies_mL", groupvars=c("site", "date"))

vp_sum <- summarySE(vp, measurevar="copies_mL", groupvars=c("site", "date")) %>%
  filter(!site %in% "Blind Oso") #Non-detects at this site

vv_sum <- summarySE(vv, measurevar="copies_mL", groupvars=c("site", "date"))
```

#### Combine above/below data with sum data

```{r}
va_sum<-
  va_sum %>%full_join(va1)

vc_sum<-
  vc_sum %>%full_join(vc1)

vp_sum<-
  vp_sum %>%full_join(vp1)

vv_sum<-
  vv_sum %>%full_join(vv1)
```

# Plot

```{r}
cbbPalette <- c("#DDAA33", "#BB5566", "#004488" )
cbbPalette2 <-c( "#BB5566", "#004488" )
```

```{r}
pd <- position_dodge(0.1) # move lines .05 to the left and right
```

**We will be plotting Standard Error (SE)**

#### Vv

```{r}
vv_sum1<-
  vv_sum %>%
  filter(!site %in% "Blind Oso")

vv_c2_rd<-
ggplot(vv_sum1, 
       aes(x=date, 
           y=copies_mL, 
           color=site)) + 
    geom_errorbar(data = vv_sum1[vv_sum1$point_shape == "16",],
      aes(ymin=copies_mL-se, 
          ymax=copies_mL+se), 
      size = 1,
      width=0.3) +
    geom_errorbar( data = vv_sum1[vv_sum1$point_shape == "1" ,],
      aes(ymin=0, 
          ymax=0, 
      width=0)) +
    geom_line(size = 1) +
    geom_point(data = vv_sum1, shape= vv_sum1$point_shape, size = 2.5)+
  theme_bw()+
  labs(x = "Date",
       y = "V. vulnificus (copies/mL)",
       color = "Site")+
  scale_x_date(date_breaks = "2 day", date_labels = "%b %d")+
  scale_color_manual(values = cbbPalette2)+
  theme(axis.text.x = element_text(size =10),
        axis.title.x = element_text(size = 13),
        axis.title.y = element_text(size = 13,face = "bold"),
        axis.text.y = element_text(size = 10),
        legend.position = "none") 

vv_c2_rd
```

```{r}

vv_sum1<-
  vv_sum %>%
  filter(site %in% "Blind Oso")

vv_bo<-
ggplot(vv_sum1, 
       aes(x=date, 
           y=copies_mL, 
           color=site)) + 
    geom_errorbar(data = vv_sum1[vv_sum1$point_shape == "16",],
      aes(ymin=copies_mL-se, 
          ymax=copies_mL+se), 
      width=0.3,
      size = 1) +
    geom_errorbar( data = vv_sum1[vv_sum1$point_shape == "1" ,],
      aes(ymin=0, 
          ymax=0, 
      width=0)) +
    geom_line(size = 1) +
    geom_point(data = vv_sum1, shape= vv_sum1$point_shape, size = 2.5)+
  theme_bw()+
  labs(x = "Date",
       y = "V. vulnificus (copies/mL)",
       color = "Site")+
  scale_x_date(date_breaks = "2 day", date_labels = "%b %d")+
  scale_color_manual(values = cbbPalette)+
  theme(#axis.text.x = element_blank(),
        axis.title.x = element_blank(),
       # axis.ticks.x = element_blank(),
        axis.title.y = element_text(size = 13, face = "bold"),
        axis.text.y = element_text(size = 10),
        legend.position = "none") 
vv_bo
```

#### Va

```{r, include=FALSE}
va_p<-
ggplot(va_sum, 
       aes(x=date, 
           y=log10(copies_mL), 
           color=site)) + 
    geom_errorbar(data = va_sum[va_sum$point_shape == "16",],
      aes(ymin=log10(copies_mL-se), 
          ymax= log10(copies_mL+se)), 
      width=0.3) +
    geom_errorbar( data = va_sum[va_sum$point_shape == "1" ,],
      aes(ymin=0, 
          ymax=0), 
      width=0) +
    geom_line() +
    geom_point(data = va_sum, shape= va_sum$point_shape, size = 2)+
  theme_bw()+
  labs(y = "log10(V. alginolyticus)",
       color = "Site")+
  scale_x_date(date_breaks = "2 day", date_labels = "%b %d")+
scale_color_manual(values = cbbPalette)+
  theme(axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.title.x = element_blank(),
        legend.position = "none") 
va_p
```

#### Vc

```{r}
vc_sum1<-
  vc_sum %>%
  filter(site %in% "Blind Oso")

vc_bo<-
ggplot(vc_sum1, 
       aes(x=date, 
           y=copies_mL, 
           color=site)) + 
    geom_errorbar(data = vc_sum1[vc_sum1$point_shape == "16",],
      aes(ymin=copies_mL-se, 
          ymax=copies_mL+se), 
      width=0.3,
      size = 1) +
    geom_errorbar( data = vc_sum1[vc_sum1$point_shape == "1" ,],
      aes(ymin=0, 
          ymax=0), 
      width=0) +
    geom_line(size = 1) +
    geom_point(data = vc_sum1, shape= vc_sum1$point_shape, size = 2.5)+
  theme_bw()+
  labs(x = "Date",
       y = "V. cholerae (gene copies/mL)",
       color = "Site")+
  scale_x_date(date_breaks = "2 day", date_labels = "%b %d")+
  scale_color_manual(values = cbbPalette)+
  theme(#axis.text.x = element_blank(),
        #axis.ticks.x = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_text(size = 13, face = "bold"),
        axis.text.y = element_text(size = 10),
        legend.position = "none")
vc_bo
```

```{r}
vc_sum1<-
  vc_sum %>%
  filter(!site %in% "Blind Oso")

vc_c2_rd<-
ggplot(vc_sum1, 
       aes(x=date, 
           y=copies_mL, 
           color=site)) + 
    geom_errorbar(data = vc_sum1[vc_sum1$point_shape == "16",],
      aes(ymin=copies_mL-se, 
          ymax=copies_mL+se), 
      width=0.3,
      size = 1) +
    geom_errorbar( data = vc_sum1[vc_sum1$point_shape == "1" ,],
      aes(ymin=0, 
          ymax=0), 
      width=0) +
    geom_line(size = 1) +
    geom_point(data = vc_sum1, shape= vc_sum1$point_shape, size = 2.5)+
  theme_bw()+
  labs(x = "Date",
       y = "V. cholerae (gene copies/mL)",
       color = "Site")+
  scale_x_date(date_breaks = "2 day", date_labels = "%b %d")+
  scale_color_manual(values = cbbPalette2)+
  theme(axis.text.x = element_text(size = 10),
        #axis.ticks.x = element_blank(),
        axis.title.x = element_text(size = 13),
        axis.title.y = element_text(size = 13, face = "bold"),
        axis.text.y = element_text(size = 10),
        legend.position = "none")
vc_c2_rd
```

#### Vp

```{r, include=FALSE}
vp_p<-
ggplot(vp_sum, 
       aes(x=date, 
           y=log10(copies_mL), 
           color=site)) + 
    geom_errorbar(data = vp_sum[vp_sum$point_shape == "16",],
      aes(ymin= log10(copies_mL-se), 
          ymax= log10(copies_mL+se)), 
      width=0.3) +
    geom_errorbar( data = vp_sum[vp_sum$point_shape == "1" ,],
      aes(ymin=0, 
          ymax=0), 
      width=0) +
    geom_line() +
    geom_point(data = vp_sum, shape= vp_sum$point_shape, size = 2)+
  theme_bw()+
  labs(x = "Date",
       y = "log10(V. parahaemolyticus)",
       color = "Site")+
  scale_x_date(date_breaks = "2 day", date_labels = "%b %d")+
  scale_color_manual(values = cbbPalette)+ 
  theme(axis.text.x = element_text(hjust = 1, angle = 45),
        legend.position = "none")
vp_p
```

#### Combine

```{r, fig.height= 3}
ggarrange(vc_bo, vv_bo, vc_c2_rd, vv_c2_rd,
          nrow = 2,
          ncol = 2,
          #common.legend = TRUE,
          align = "hv")

ggsave(here('results', 'plots','qpcr', 'species', 'species_SE_plots.png' ))
```

## Per Pos

**Vc**

```{r}
vc_pp<-
  vc1 %>% 
 # filter(site %in% "Cana") %>%
  ggplot() +
  geom_bar(
    aes(x = date,
        y = per_pos*100,
    fill = site),
    stat = "identity") + facet_wrap(~site) +
  scale_fill_manual(values = cbbPalette)+
  theme_bw()+
  theme(legend.position = "none",
        axis.title.y = element_text(face = "bold"),
        axis.text.x = element_blank(),
        plot.title = element_text(hjust = 0.5),
        axis.ticks.x = element_blank())+
  labs(x = "",
       y = "% Positivity (n = 5)",
       title = "V. cholerae: % Positivity of qPCR replicates")+
  scale_x_date(date_breaks = "2 days", date_labels = "%b %d")+
  ylim(0,100)
```

**Vv**

```{r}
vv_pp<-
  vv1 %>% 
 # filter(site %in% "Cana") %>%
  ggplot() +
  geom_bar(
    aes(x = date,
        y = per_pos*100,
    fill = site),
    stat = "identity") + facet_wrap(~site) +
  scale_fill_manual(values = cbbPalette)+
  theme_bw()+
  theme(legend.position = "none",
        axis.title.y = element_text(face = "bold"),
        axis.text.x = element_text(hjust =1, angle = 45),
        axis.title.x = element_blank(),
        plot.title = element_text(hjust = 0.5))+
  labs(
       y = "% Positivity (n = 3)",
       title = "V. vulnificus: % Positivity of qPCR replicates")+
  scale_x_date(date_breaks = "2 days", date_labels = "%b %d") +
  ylim(0,100)
```

```{r}
ggarrange(vc_pp, vv_pp,
          ncol = 1, nrow = 2,
          align = "v")
```
