---
title: "vp daily"
format:
  html:
    theme: default
---

# LIBS/DATA

#### LIBRARIES

```{r}
library(here)
library(tidyverse)
library(lubridate)
library(ggpubr) #Stacking Plots
```

#### DATA

```{r}
vp<- read_csv(here("data", "processed_data","vp_clean_copies.csv"))
vp_m<- read_csv(here("data", "processed_data","vp_mon_clean_copies.csv")) 

vv<- read_csv(here("data", "processed_data","vv_clean_copies_redo.csv")) #Trial two is best. Other trials exist too. 
vv_m<- read_csv(here("data", "processed_data","vv_clean_copies_mon.csv"))

vc<- read_csv(here("data", "processed_data", "vc_clean_copies_daily.csv"))
vc_m<- read_csv(here("data", "processed_data", "vc_clean_copies_mon.csv"))
vc_bo<- read_csv(here("data", "processed_data","vc_clean_copies_dail_1_50.csv")) #Ran 1:50. still had inhibition
vc_b100<- read_csv(here("data", "processed_data","vc_clean_copies_daily_1_100.csv")) #Ran 1:100.

va<- read_csv(here("data", "processed_data", "va_clean_copies_daily.csv"))
va_m<-  read_csv(here("data", "processed_data", "va_clean_copies_monthly.csv"))
```

# CLEANING

#### Clean Daily data sets

```{r}
vv<- vv %>%
  mutate(site = recode(site, "BO" = "Blind Oso")) %>%
  mutate(site = recode(site, "C2" = "Canals")) %>%
  mutate(site = recode(site, "RD" = "Gulf"))

vp<- vp %>%
  mutate(site = recode(site, "BO" = "Blind Oso")) %>%
  mutate(site = recode(site, "C2" = "Canals")) %>%
  mutate(site = recode(site, "RD" = "Gulf"))

vc<- vc %>%
  mutate(site = recode(site, "BO" = "Blind Oso")) %>%
  mutate(site = recode(site, "C2" = "Canals")) %>%
  mutate(site = recode(site, "RD" = "Gulf"))
vc_bo<- vc_bo %>%
  mutate(site = recode(site, "BO" = "Blind Oso")) %>%
  mutate(site = recode(site, "C2" = "Canals")) %>%
  mutate(site = recode(site, "RD" = "Gulf"))
vc_b100<- vc_b100 %>%
  mutate(site = recode(site, "BO" = "Blind Oso")) %>%
  mutate(site = recode(site, "C2" = "Canals")) %>%
  mutate(site = recode(site, "RD" = "Gulf"))

va<- va %>%
  mutate(site = recode(site, "BO" = "Blind Oso")) %>%
  mutate(site = recode(site, "C2" = "Canals")) %>%
  mutate(site = recode(site, "RD" = "Gulf"))
```

#### Add July to Monthly Data

```{r}
#Vp Mon
vp_m<- vp_m %>%
  select(!...1) 
jul_bo = data.frame(date = as.Date("2022-07-07"), copies_mL=0, site = "BO")
jul_c2 = data.frame(date = as.Date("2022-07-07"), copies_mL=0, site = "C2")
jul_rd = data.frame(date = as.Date("2022-07-07"), copies_mL=7.49310194, site = "RD")
vp_m = rbind(jul_bo, jul_c2, jul_rd, vp_m) %>%
  mutate(site = recode(site, "BO" = "Blind Oso")) %>%
  mutate(site = recode(site, "C2" = "Canals")) %>%
  mutate(site = recode(site, "RD" = "Gulf"))
                     

#Vv Mon
vv_m<- vv_m %>%
  select(!...1) 
jul_bo = data.frame(date = as.Date("2022-07-07"), copies_mL=0, site = "BO")
jul_c2 = data.frame(date = as.Date("2022-07-07"), copies_mL=0, site = "C2")
jul_rd = data.frame(date = as.Date("2022-07-07"), copies_mL=7.49310194, site = "RD")
vv_m = rbind(jul_bo, jul_c2, jul_rd, vv_m)%>%
  mutate(site = recode(site, "BO" = "Blind Oso")) %>%
  mutate(site = recode(site, "C2" = "Canals")) %>%
  mutate(site = recode(site, "RD" = "Gulf"))

vc_m<- vc_m %>%
  select(!...1) 
  jul_bo = data.frame(date = as.Date("2022-07-07"), copies_mL=263.208407, site = "BO")
  jul_c2 = data.frame(date = as.Date("2022-07-07"), copies_mL=0, site = "C2")
  jul_rd = data.frame(date = as.Date("2022-07-07"), copies_mL=0, site = "RD")
  vc_m = rbind(jul_bo, jul_c2, jul_rd, vc_m)%>%
    mutate(site = recode(site, "BO" = "Blind Oso")) %>%
    mutate(site = recode(site, "C2" = "Canals")) %>%
    mutate(site = recode(site, "RD" = "Gulf"))
  
 va_m<- va_m %>%
  select(!...1) 
  jul_bo = data.frame(date = as.Date("2022-07-07"), copies_mL=0, site = "BO")
  jul_c2 = data.frame(date = as.Date("2022-07-07"), copies_mL=5.494766, site = "C2")
  jul_rd = data.frame(date = as.Date("2022-07-07"), copies_mL=0, site = "RD")
  va_m = rbind(jul_bo, jul_c2, jul_rd, va_m)%>%
    mutate(site = recode(site, "BO" = "Blind Oso")) %>%
    mutate(site = recode(site, "C2" = "Canals")) %>%
    mutate(site = recode(site, "RD" = "Gulf")) 
```

# DAILY PLOTS

## Vp

```{r}
png(file = here("results", "plots", "species_specific", "vp_daily.png"))
vp_d<- vp %>%
  ggplot() + geom_line(
    aes(x = date,
        y = copies_mL,
        color = site))+ 
  facet_wrap(~site)  +
  labs(x = "Date",
       y = "Copies/mL",
       title = "Daily Vibrio parahaemolyticus")+
  theme_bw()+
  theme(
    plot.title = element_text(hjust = 0.5),
    axis.text.x = element_text(hjust = 1, angle = 45),
    legend.position = "none")+
  scale_color_manual(values = c("Blind Oso" = "#809C52",
                                "Canals" = "#ba4716",
                                "Gulf" = "4c848c"))
dev.off()
vp_d
```

## Vv

```{r}
png(file = here("results", "plots", "species_specific", "vv_daily.png"))

vv_d<- vv %>%
  #filter(!site %in% "Blind Oso") %>%
  ggplot() + geom_line(
    aes(x = date,
        y = copies_mL,
        color = site))+ 
  facet_wrap(~site)  +
  labs(x = "Date",
       y = "Copies/mL",
       title = "Daily Vibrio vulnificus")+
  theme_bw()+
  theme(
    plot.title = element_text(hjust = 0.5),
    axis.text.x = element_text(hjust = 1, angle = 45),
    legend.position = "none")+ 
  scale_color_manual(values = c("Blind Oso" = "#809C52",
                                "Canals" = "#ba4716",
                                "Gulf" = "4c848c"))
dev.off()
vv_d
```

## Vc

#### Trial 1

```{r}
t1<-vc %>%
filter(site %in% "Blind Oso") %>%
  ggplot() + geom_line(
    aes(x = date,
        y = copies_mL,
        color = site))+ 
  facet_wrap(~site)  +
  labs(x = "Date",
       y = "Copies/mL",
       title = "Trial 1",
       caption = "Blind Oso was 1:10")+
  theme_bw()+
  theme(
    plot.title = element_text(hjust = 0.5),
    axis.text.x = element_text(hjust = 1, angle = 45),
    legend.position = "none")+ 
  scale_color_manual(values = c("Blind Oso" = "#809C52",
                                "Canals" = "#ba4716",
                                "Gulf" = "4c848c"))
```

#### Trial 2: Just BO 1:50

```{r}
png(file = here("results", "plots", "species_specific", "vc_daily.png"))

 vc_bo %>%
  ggplot() + geom_line(
    aes(x = date,
        y = copies_mL,
        color = site))+ 
  facet_wrap(~site)  +
  labs(x = "Date",
       y = "Copies/mL",
       title = "Trial 2",
       caption = "Blind Oso was 1:50")+
  theme_bw()+
  theme(
    plot.title = element_text(hjust = 0.5),
    axis.text.x = element_text(hjust = 1, angle = 45),
    legend.position = "none")+ 
  scale_color_manual(values = c("Blind Oso" = "#809C52"))
dev.off()

```

This seems to follow a more expected trend. But we still have inhibition (see inhibition code). I am going to try a 1:100 dilution.

#### Trial 3: Just BO 1:100

```{r}
t3<- vc_b100 %>%
  ggplot() + geom_line(
    aes(x = date,
        y = copies_mL,
        color = site))+ 
  facet_wrap(~site)  +
  labs(x = "Date",
       y = "Copies/mL",
       title = "Trial 3",
       caption = "Blind Oso was 1:100")+
  theme_bw()+
  theme(
    plot.title = element_text(hjust = 0.5),
    axis.text.x = element_text(hjust = 1, angle = 45),
    legend.position = "none")+ 
  scale_color_manual(values = c("Blind Oso" = "#809C52"))
```

#### Stack

```{r, fig.height= 8, fig.width= 8}
fig<- 
  ggarrange(t1, t2, t3 + font("x.text", size = 10), ncol = 1, nrow = 3)
fig

```

## Va

```{r}
png(file = here("results", "plots", "species_specific", "va_daily.png"))

va_d<- va %>%
 #filter(!site %in% "Blind Oso") %>%
  ggplot() + geom_line(
    aes(x = date,
        y = copies_mL,
        color = site))+ 
  facet_wrap(~site)  +
  labs(x = "Date",
       y = "Copies/mL",
       title = "Daily Vibrio alginolyticus")+
  theme_bw()+
  theme(
    plot.title = element_text(hjust = 0.5),
    axis.text.x = element_text(hjust = 1, angle = 45),
    legend.position = "none")+ 
  scale_color_manual(values = c("Blind Oso" = "#809C52",
                                "Canals" = "#ba4716",
                                "Gulf" = "4c848c"))
dev.off()
va_d
```

## Combine all species

#### Combine dataset

```{r}
#Make new columns with species 
type = "vc"
vc1<- cbind(vc, type)

type = "vv"
vv1<- cbind(vv, type)

type = "vp"
vp1<- cbind(vp, type)

type = "va"
va1<- cbind(va,type)

#Combine datasets
master<- rbind(vc1,vp1,vv1, va1)
```

#### Plot

##### Blind Oso

```{r}
png(file = here("results", "plots", "species_specific", "bo_daily.png"))

bo_daily<- master %>%
  filter(site %in% "Blind Oso")%>%
  ggplot() + geom_line(
    aes(
      x = date,
      y = copies_mL,
      color = type))+ 
  theme_bw()+
  theme(
    axis.text.x = element_text(hjust = 1, angle = 45))

dev.off()
bo_daily
```

##### Canals

```{r}
png(file = here("results", "plots", "species_specific", "c2_daily.png"))

c2_daily<- master %>%
  filter(site %in% "Canals")%>%
  ggplot() + geom_line(
    aes(
      x = date,
      y = copies_mL,
      color = type))+ 
  theme_bw()+
  theme(
    axis.text.x = element_text(hjust = 1, angle = 45))

dev.off()
c2_daily
```

##### Gulf

```{r}
png(file = here("results", "plots", "species_specific", "rd_daily.png"))

rd_daily<- master %>%
  filter(site %in% "Gulf")%>%
  ggplot() + geom_line(
    aes(
      x = date,
      y = copies_mL,
      color = type))+ 
  theme_bw()+
  theme(
    axis.text.x = element_text(hjust = 1, angle = 45))

dev.off()
rd_daily
```

# MONTHLY PLOTS

#### Vp

```{r}
png(file = here("results", "plots", "species_specific", "vp_mon.png"))

vp_mon<- vp_m %>%
ggplot() + geom_line(
    aes(x = date,
        y = copies_mL,
        color = site))+ 
  geom_point(
     aes(x = date,
        y = copies_mL,
        color = site))+
  facet_wrap(~site)  +
  labs(x = "Date",
       y = "Copies/mL",
       title = "Monthly Vibrio parahaemolyticus")+
  theme_bw()+
  theme(
    plot.title = element_text(hjust = 0.5),
    axis.text.x = element_text(hjust = 1, angle = 45),
    legend.position = "none")+
  scale_color_manual(values = c("Blind Oso" = "#809C52",
                                "Canals" = "#ba4716",
                                "Gulf" = "4c848c"))+
  scale_x_date(date_breaks = "1 month", date_labels = "%b")

dev.off()
vp_mon
```

#### Vv

```{r}
png(file = here("results", "plots", "species_specific", "vv_mon.png"))
vv_mon<- vv_m %>%
  filter(!site %in% c("E3", "NT")) %>%
 ggplot() + geom_line(
    aes(x = date,
        y = copies_mL,
        color = site))+ 
  geom_point(
     aes(x = date,
        y = copies_mL,
        color = site))+
  facet_wrap(~site)  +
  labs(x = "Date",
       y = "Copies/mL",
       title = "Monthly Vibrio vulnificus")+
  theme_bw()+
  theme(
    plot.title = element_text(hjust = 0.5),
    axis.text.x = element_text(hjust = 1, angle = 45),
    legend.position = "none")+
  scale_color_manual(values = c("Blind Oso" = "#809C52",
                                "Canals" = "#ba4716",
                                "Gulf" = "4c848c"))+
  scale_x_date(date_breaks = "1 month", date_labels = "%b")
dev.off()
vv_mon
```

#### Vc

```{r}
png(file = here("results", "plots", "species_specific", "vc_mon.png"))
vc_mon<- vc_m %>%
  #filter(!site %in% "Blind Oso") %>%
 ggplot() + geom_line(
    aes(x = date,
        y = copies_mL,
        color = site))+ 
  geom_point(
     aes(x = date,
        y = copies_mL,
        color = site))+
  facet_wrap(~site)  +
  labs(x = "Date",
       y = "Copies/mL",
       title = "Monthly Vibrio cholerae")+
  theme_bw()+
  theme(
    plot.title = element_text(hjust = 0.5),
    axis.text.x = element_text(hjust = 1, angle = 45),
    legend.position = "none")+
  scale_color_manual(values = c("Blind Oso" = "#809C52",
                                "Canals" = "#ba4716",
                                "Gulf" = "4c848c"))+
  scale_x_date(date_breaks = "1 month", date_labels = "%b")
dev.off()
vc_mon
```

#### Va

```{r}
png(file = here("results", "plots", "species_specific", "va_mon.png"))
va_mon<- va_m %>%
  #filter(!site %in% "Blind Oso") %>%
 ggplot() + geom_line(
    aes(x = date,
        y = copies_mL,
        color = site))+ 
  geom_point(
     aes(x = date,
        y = copies_mL,
        color = site))+
  facet_wrap(~site)  +
  labs(x = "Date",
       y = "Copies/mL",
       title = "Monthly Vibrio alginolyticus")+
  theme_bw()+
  theme(
    plot.title = element_text(hjust = 0.5),
    axis.text.x = element_text(hjust = 1, angle = 45),
    legend.position = "none")+
  scale_color_manual(values = c("Blind Oso" = "#809C52",
                                "Canals" = "#ba4716",
                                "Gulf" = "4c848c"))+
  scale_x_date(date_breaks = "1 month", date_labels = "%b")
dev.off()
va_mon
```
