---
title: "Exploratory"
format:
  html:
    theme: default
---

\*\*This code looks at Vibrio enumeration over the daily time series. This information can also be found in `dust_and_copies.qmd` Library

```{r}
library(tidyverse)
library(here)
```

#### Load Data

```{r}
data<- read_csv(here("data", "processed_data", "tx_master.csv")) 
```

# Clean

#### Make mini dataframes for each site

```{r}
#Daily All Sites
daily<- data %>%
  select(date,copies_mL,site,Type) %>%
  filter(Type %in% "Daily") %>%
drop_na() #Get rid of NAs


#Daily by Site
bo_daily <- daily %>% filter(site %in% "Blind Oso") #Blind Oso Bay
c2_daily <- daily %>% filter(site %in% "Canals") #Canals
rd_daily <- daily %>% filter(site %in% "Gulf") #Gulf Site



```

# Plot

#### Total Daily Vibrio at Gulf

```{r}
rd_daily %>%
  ggplot() +geom_line(
    aes(x = date,
        y = copies_mL),
    color = "4c848c",
    size = 1) +
  theme_bw() +
  labs(
    x = "Date",
    y = "Vibrio gene copies/mL",
    title = "Total Vibrio Concentrations at the Gulf") +
  theme(plot.title = element_text(hjust = 0.5))
```

#### Total Daily Vibrio at Canals

```{r}
c2_daily %>%
  ggplot() +geom_line(
    aes(x = date,
        y = copies_mL),
    color = "#ba4716",
    size = 1) +
  theme_bw() +
  labs(
    x = "Date",
    y = "Vibrio gene copies/mL",
    title = "Total Vibrio Concentration at the Canals") +
  theme(plot.title = element_text(hjust = 0.5))
```

#### Total Daily Vibrio at Blind Oso

```{r}
bo_daily %>%
  ggplot() +geom_line(
    aes(x = date,
        y = copies_mL),
    color = "#809C52",
    size = 1) +
  theme_bw() +
  labs(
    x = "Date",
    y = "Vibrio gene copies/mL",
    title = "Total Vibrio Concentrations at Blind Oso") +
  theme(plot.title = element_text(hjust = 0.5))
```

#### Total Daily Vibrio

```{r}
tot_vib<- daily %>% ggplot()+geom_line(
  aes(x = date,
      y = copies_mL,
      color = site))+
  #facet_wrap(~site) +
  theme_bw()+
  labs(
    x = "Date",
    y = "Copies/mL",
    title = "Total Daily Vibrio at all Sites") +
  theme(plot.title = element_text(hjust = 0.5)) + #center title
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) + #Tilt x axis labels 
 # theme(legend.position = "none") + #Removes legend 
  scale_color_manual(values = c("Blind Oso" = "#809C52",
                                "Canals" = "#ba4716",
                                "Gulf" = "#4c848c"))

tot_vib

ggsave(here("results", "plots", "qpcr", "total_vib_daily.png"))
```

# Make clean DF for writing

```{r}
b<- unique(bo_daily)
c<- unique(c2_daily)
r<- unique(rd_daily)
```

#### Averages

```{r}
mean(b$copies_mL)
mean(c$copies_mL)
mean(r$copies_mL)
```
