---
title: "Untitled"
format:
  html:
    theme: default
---

# Intro

#### Libs

```{r}
library(here)
library(tidyverse)
```

#### Data

```{r}
d<- read_csv(here("data", "raw_data", "qpcr", "va","va_diluted_down_strains.csv"))
g<- read_csv(here("data", "raw_data", "qpcr", "va","va_gblock.csv"))
grad<- read_csv(here("data", "raw_data", "qpcr", "va","va_gradient.csv"))
```

# Cleaning

```{r}
d<-
  d %>%
  select(Sample, Cq)

g<-
  g %>%
  select(concentration, Cq)

grad<-
  grad %>%
  select(Well, Sample, Cq)
```

```{r}
d<-
  d %>%
  mutate(strain = substr(Sample, 1,3),
         dilution = substr(Sample, 4,5)) 

g<-
  g %>%
  mutate(strain = "Gblock") %>%
  filter(!is.na(Cq))

grad<-
  grad %>%
  mutate(temp = case_when(grepl("A", Well) ~ "65",
         grepl("D", Well) ~ "64.1",
         grepl("F", Well) ~ "62.7",
         grepl("H", Well) ~ "60.6",
         grepl("J", Well) ~ "58.4",
         grepl("L", Well) ~ "56.8",
         grepl("P", Well) ~ "55"),
         Sample = recode(Sample, "e4" = "10^4"),
         Sample = recode(Sample, "e3" = "10^3"),
         Sample = recode(Sample, "e2" = "10^2"),
         Sample = recode(Sample, "e1" = "10^1"),
         Sample = recode(Sample, "e0" = "10^0"),
         Sample = recode(Sample, "Raw" = "10^5"),
         Sample = recode(Sample, "Raw_e5" = "10^5")) %>%
  filter(!Sample %in% "NTC") 
```

```{r}
d$strain<- gsub('_', '', d$strain)
d$dilution<- gsub('_', '', d$dilution)

d<-
  d %>%
  mutate(concentration = case_when(dilution == "1" ~ "10^4",
                                   dilution == "2" ~ "10^3",
                                   dilution == "3" ~ "10^2",
                                   dilution == "4" ~ "10^1")) %>%
  select(!c(Sample, dilution))
```

```{r}
df_line <- grad %>% group_by(Sample) %>% summarise(mean_y = mean(Cq))
```

```{r}
master<-
  rbind(d,g)
```

# Plot

```{r}
master %>%
  ggplot() + geom_boxplot(
    aes(x = concentration,
        y = Cq,
        color = strain)) +
  theme_bw() +
  labs(x = "Estimated Concentration (CFU/µL)",
       title = "V. alginolyticus strains diluted down",
       color = "Strain") +
  scale_x_discrete(limits = c("10^6", "10^5", "10^4", "10^3", "10^2", "10^1", "10^0", "10^-1"))

```

```{r}
grad %>%
  ggplot() +
  geom_boxplot(
    aes(x = Sample,
        y = Cq,
        color = temp),
    size = 0.75) + 
  theme_bw() +
  labs(x = "Estimated Concentration (CFU/µL)",
       title = "EKL99 Temperature Gradient Experiment",
       color = "Temperature") +
  scale_x_discrete(limits = c("10^4", "10^3", "10^2", "10^1", "10^0"))
```
