---
title: "VAI"
format:
  html:
    theme: default
---

**Viz VAI**

# Intro

#### LIbrary

```{r}
library(here)
library(tidyverse)
```

#### Data

```{r, include = FALSE}
master<- read_csv(here("data", "processed_data", "tx_master.csv"))
```

# Cleaning

#### Daily DF

```{r}
daily<-
  master %>%
  filter(date %in% as.Date('2022-07-07') : as.Date('2022-07-19'),
         hr_cst %in% "01",
         !date %in% as.Date('2022-07-10'))
```

# Plot

```{r}
daily %>%
  ggplot() + geom_bar(
    aes(x = date,
        y = VAI,
        fill = site),
    color = "black",
    stat = "identity") +
  facet_wrap(~site) +
  theme_bw() + 
  labs(title = "Daily VAI",
       fill = "Site",
       x = "Date")+
  theme(plot.title = element_text(hjust = 0.5),
        axis.title.y = element_text(face = "bold"),
        axis.title.x = element_text(face = "bold"),
        axis.text.x = element_text(angle = 45, hjust = 1)) +
  scale_fill_manual(values = c("Blind Oso" = "#809C52",
                                "Canals" = "#ba4716",
                                "Gulf" = "4c848c")) +
  scale_x_date(date_breaks = "2 day", date_labels = "%b%d")

  ggsave(here("results", "plots", "qpcr", "vai.png"))
```
